default:
  threads: 1
  mem_mb: 1024
  time: "01:00:00"
rules:
  bwa_mem:
    threads: 4
    mem_mb: 8192
    time: "08:00:00"
  mark_duplicates:
    mem_mb: 6144
  bqsr:
    mem_mb: 4096
  mutect2:
    threads: 2
    mem_mb: 8192
    time: "12:00:00"
  haplotype_caller:
    mem_mb: 8192
  manta_sv:
    threads: 4
    mem_mb: 4096
